### ISSUE TITLE
Not able to install agent-protocol

### ISSUE THREAD

**Issue by Aayushyaverma** [AI-Engineers-Foundation/agent-protocol#61]
Now I have been trying to install this on my system with pip install agent-protocol bu it generates the following output: 
`.venv) ayushyaverma@Ayushyas-MacBook-Pro Auto-GPT % pip install agent-protocol

ERROR: Could not find a version that satisfies the requirement agent-protocol (from versions: none)
ERROR: No matching distribution found for agent-protocol
(.venv) ayushyaverma@Ayushyas-MacBook-Pro Auto-GPT % pip3 install agent-protocol

ERROR: Could not find a version that satisfies the requirement agent-protocol (from versions: none)
ERROR: No matching distribution found for agent-protocol`

Please help.

Also it's my first time raising an issue anywhere on github, sorry if this doesn't fit the standard.

**Comment by Kalcinator** [comment]
ERROR: Could not find a version that satisfies the requirement agent-protocol-client (from versions: none)
ERROR: No matching distribution found for agent-protocol-client
For myself ...

**Comment by Kalcinator** [comment]
[site-packages.zip](https://github.com/AI-Engineers-Foundation/agent-protocol/files/12641076/site-packages.zip)

**Comment by assilbegmoneybounce** [comment]
Hello i am having exactly this issue.
when i tried installing your package i got ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
I am not a confirmed developer so i might have done things wrong, however i did open the terminal on your folder... if that makes sense
begging for help :')

**Comment by seba90** [comment]
Same issue here. Trying to get AutoGPT to install but it fails due to the mentioned error.

**Comment by kingrat432** [comment]
Me too, same issue. Chat GPT says:
To resolve this issue, you have a few options:

Wait for Package Availability: You can wait for the maintainers of the agent-protocol package to address the issue and make it available on PyPI. This may take some time, but it's the most straightforward solution.

Manual Installation: If you have access to the package files or a working copy from another source, you can manually install it as I mentioned earlier. This involves downloading the package from GitHub and installing it using pip with the -e flag. You mentioned that you tried this, but if it's not working, you may want to ensure you have the correct source files and that there's a setup.py or pyproject.toml file in the package directory.

Contact the Maintainers: You can try contacting the maintainers of the agent-protocol package through their GitHub repository or other communication channels to inquire about the availability and installation issues.

Please note that the availability of external packages like agent-protocol depends on the package's maintainers and its compatibility with your environment. You may want to periodically check for updates or alternative solutions as the situation evolves.

**Comment by Kalcinator** [comment]
Guys juste use the files I gave you ! 
Obviously you can't really trust me I understand but it worked ! I even went to discord to ask and talked about it !!
https://discord.com/channels/1092243196446249134/1147218449072914563/1152705394087563357

**Comment by assilbegmoneybounce** [comment]
> Guys juste use the files I gave you ! Obviously you can't really trust me I understand but it worked ! I even went to discord to ask and talked about it !! https://discord.com/channels/1092243196446249134/1147218449072914563/1152705394087563357

okay, but how am i supposed to use your file exactly ? I am not a developer and even with chatgpt i am struggling..

**Comment by Kalcinator** [comment]
You need to install the files in Python311\Lib\site-packages

**Comment by Aayushyaverma** [comment]
how do i install this in mac

**Comment by ATheorell** [comment]
@Kalcinator , thx for the quick fix, but I don't consider this a solution to the problem of agent-protocol no longer featuring on pypi.

**Comment by Kalcinator** [comment]
> @Kalcinator , thx for the quick fix, but I don't consider this a solution to the problem of agent-protocol no longer featuring on pypi.

At least it's working for now bro ... 
But yeah pypi deleting agent-protocol is giga weird;
We can see the instability of our technology now, Auto-GPT is powerful but just remove one tiny box and it's falling apart ...

**Comment by hackgoofer** [comment]
Hi! We released the agent-protocol v1.0.0 today; You can download with `pip install agent-protocol`, this installs the agent-protocol-sdk-python https://github.com/AI-Engineers-Foundation/agent-protocol-sdk-python
