### ISSUE TITLE
Question: Can agents create steps or tasks for itself?

### ISSUE THREAD

**Issue by thomafred** [AI-Engineers-Foundation/agent-protocol#64]
Does the protocol any restrictions to whether an agent can create tasks or steps for itself? How does this relate to the `is_last`-flag?

**Comment by hackgoofer** [comment]
Yes. The way task/step delineation is that a task is created by the external (another agent or human). Once a task is created, the agents will have many steps associated with the task. And you can call "create step" to execute the steps.

**Comment by hackgoofer** [comment]
I am closing the issue, please reopen if you have additional questions!

**Comment by thomafred** [comment]
@hackgoofer Thanks for the clarification.

I guess my confusion revolves around the `last_step`-flag. In what circumstances does the agent set this flag to `true`, and what implications does this have? Can we for example start cleaning up resources at this point?

In half-duplex systems such as walkie-talkies for example, protocol dictates that the person starting a conversation is also the one ending it.
